server:
  port: 8080

spring:
  profiles:
    active: test

springdoc:
  swagger-ui:
    path: /vpc

holidays:
  dates:
    - 2025-01-01  # 1 января - Новогодние каникулы
    - 2025-01-02  # 2 января - Новогодние каникулы
    - 2025-01-03  # 3 января - Новогодние каникулы
    - 2025-01-04  # 4 января - Новогодние каникулы
    - 2025-01-05  # 5 января - Новогодние каникулы
    - 2025-01-06  # 6 января - Новогодние каникулы
    - 2025-01-08  # 8 января - Новогодние каникулы
    - 2025-01-07  # 7 января - Рождество Христово
    - 2025-02-23  # 23 февраля - День защитника Отечества
    - 2025-03-08  # 8 марта - Международный женский день
    - 2025-05-01  # 1 мая - Праздник Весны и Труда
    - 2025-05-09  # 9 мая - День Победы
    - 2025-06-12  # 12 июня - День России
    - 2025-11-04  # 4 ноября - День народного единства